### ISSUE TITLE
Data Directory Missing

### ISSUE THREAD

**Issue by genio** [servel333/node-netsuite-suitetalk-wsdl-v2017-1.0#1]
With the data directory missing, the majority of the documented features can't function:

```javascript
var wsdlOperations = wsdl.operations;
// [ "<operation name>"]

var wsdlNamespaces = wsdl.namespaces;
// { "<namespace prefix>" : "<namespace uri>" }

var wsdlComplexTypes = wsdl.complexTypes;
// { "<complex type name>" : "<namespace uri>" }

var wsdlComplexTypeNames = _.keys(wsdl.complexTypes);
```

**Comment by servel333** [comment]
You are correct. I didn't have time to add these to this version, but they are available in [the older version](https://github.com/servel333/node-netsuite-suitetalk-wsdl-v2016-2.0) (and probably nearly the same). That older version has a script [gen-schemas.js](https://github.com/servel333/node-netsuite-suitetalk-wsdl-v2016-2.0/blob/master/bin/gen-schemas.js) to help build this data and should work on this version if you need this data.

If I work with NetSuite again, I'll update this or future versions of this lib, but for now I don't have the time. Thanks for the issue.

**Comment by servel333** [comment]
Removed docs on unimplemented features.
